/// <reference path="../pb_data/types.d.ts" />
// M2a rules audit. Reasserts every list/view/create/update/delete rule across
// all collections, including `users` (which had only PB defaults until now).
// No behavior change for trips/phases/items/checklist_items beyond what 0008
// + 0013 already set; this migration's value is making intent explicit and
// adding `// reason:` notes for every intentional null. `backend/RULES.md` is
// the human-readable matrix; `backend/test-rules.mjs` is the verifier.
migrate(
	(app) => {
		// Identity expressions. Repeated literally because PB stores rule strings
		// per collection — no shared constants once saved.
		const SELF_ONLY = 'id = @request.auth.id';
		const AUTHED = '@request.auth.id != ""';
		const MEMBER = '@request.auth.id != "" && trip_members_via_trip.user ?= @request.auth.id';
		const MEMBER_VIA_TRIP =
			'@request.auth.id != "" && trip.trip_members_via_trip.user ?= @request.auth.id';
		const MEMBER_VIA_ITEM =
			'@request.auth.id != "" && item.trip.trip_members_via_trip.user ?= @request.auth.id';

		// users — auth collection, locked to self-only access.
		const users = app.findCollectionByNameOrId('users');
		users.listRule = SELF_ONLY;
		users.viewRule = SELF_ONLY;
		// reason: signup runs through OTP hook (auth.pb.js) or dev bypass, both
		// admin context. Direct API create would skip OTP verification.
		users.createRule = null;
		users.updateRule = SELF_ONLY;
		// reason: account deletion is out of scope until M6+. Leave shut.
		users.deleteRule = null;
		app.save(users);

		// trips — any authed user can create a trip; only members can read/edit.
		const trips = app.findCollectionByNameOrId('trips');
		trips.listRule = MEMBER;
		trips.viewRule = MEMBER;
		trips.createRule = AUTHED;
		trips.updateRule = MEMBER;
		trips.deleteRule = MEMBER;
		app.save(trips);

		// trip_members — read/update/delete by trip members. Create is admin-only
		// because all legitimate creation paths are server-side.
		const tripMembers = app.findCollectionByNameOrId('trip_members');
		tripMembers.listRule = MEMBER_VIA_TRIP;
		tripMembers.viewRule = MEMBER_VIA_TRIP;
		// reason: creator-owner row is added by trips after-create hook;
		// invite acceptance + placeholder claim are also hook-driven (M2b/M2c).
		// No legitimate path goes through direct client POST.
		tripMembers.createRule = null;
		tripMembers.updateRule = MEMBER_VIA_TRIP;
		tripMembers.deleteRule = MEMBER_VIA_TRIP;
		app.save(tripMembers);

		// phases — full CRUD by trip members.
		const phases = app.findCollectionByNameOrId('phases');
		phases.listRule = MEMBER_VIA_TRIP;
		phases.viewRule = MEMBER_VIA_TRIP;
		phases.createRule = MEMBER_VIA_TRIP;
		phases.updateRule = MEMBER_VIA_TRIP;
		phases.deleteRule = MEMBER_VIA_TRIP;
		app.save(phases);

		// days — read/update by trip members. Create + delete are admin-only.
		const days = app.findCollectionByNameOrId('days');
		days.listRule = MEMBER_VIA_TRIP;
		days.viewRule = MEMBER_VIA_TRIP;
		// reason: days are auto-generated by trips after-create / after-update
		// hooks based on trip date range. Users never create days directly.
		days.createRule = null;
		days.updateRule = MEMBER_VIA_TRIP;
		// reason: days are pruned by the trips after-update hook when the date
		// range shrinks. No direct delete path.
		days.deleteRule = null;
		app.save(days);

		// items — full CRUD by trip members.
		const items = app.findCollectionByNameOrId('items');
		items.listRule = MEMBER_VIA_TRIP;
		items.viewRule = MEMBER_VIA_TRIP;
		items.createRule = MEMBER_VIA_TRIP;
		items.updateRule = MEMBER_VIA_TRIP;
		items.deleteRule = MEMBER_VIA_TRIP;
		app.save(items);

		// checklist_items — full CRUD by members of the parent item's trip.
		const checklistItems = app.findCollectionByNameOrId('checklist_items');
		checklistItems.listRule = MEMBER_VIA_ITEM;
		checklistItems.viewRule = MEMBER_VIA_ITEM;
		checklistItems.createRule = MEMBER_VIA_ITEM;
		checklistItems.updateRule = MEMBER_VIA_ITEM;
		checklistItems.deleteRule = MEMBER_VIA_ITEM;
		app.save(checklistItems);
	},
	(app) => {
		// Down: clear `users` rules back to admin-only. Other collections are
		// left as 0008 + 0013 set them — those migrations are still in effect.
		const users = app.findCollectionByNameOrId('users');
		users.listRule = null;
		users.viewRule = null;
		users.createRule = null;
		users.updateRule = null;
		users.deleteRule = null;
		app.save(users);
	}
);
